{{- if .Values.serviceAccount.create -}}
{{- if .Values.tableauServer.fluentd.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tableau-server.clusterRoleName" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}
