{{- if .Values.tableauServer.fluentd.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tableau-server.fluentdName" . }}
data:
  fluentd.conf: |
  {{- .Values.tableauServer.fluentd.config.inputs | nindent 4 -}}
  {{- .Values.tableauServer.fluentd.config.outputs | nindent 4 -}}
{{- end }}
