apiVersion: v1
kind: Service
metadata:
  name: {{ include "tableau-server.fullname" . }}
  labels:
    {{- include "tableau-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "tableau-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tableau-server.fullname" . }}-gateway
  labels:
    {{- include "tableau-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tableau-server.selectorLabels" . | nindent 4 }}
