apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tableau-server.fullname" . }}-worker
  labels:
    {{- include "tableau-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tableauServer.worker.replicas }}
  serviceName: {{ include "tableau-server.fullname" . }}
  selector:
    matchLabels:
      {{- include "tableau-server.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.tableauServer.dataDir.capacity }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tableau-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tableau-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: LICENSE_KEY
              value: "not-used"
            - name: BOOTSTRAP_INSTALL
              value: {{ if .Values.tableauServer.worker.bootstrap }}"1"{{ else }}"0"{{ end }}
            - name: TSM_REMOTE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "tableau-server.fullname" . }}-{{ .Values.tableauServer.adminUserSecretNameSuffix }}"
                  key: "tsm-password"
          {{- if .Values.tableauServer.worker.probes.enabled }}
          {{- with .Values.tableauServer.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tableauServer.worker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "tableau-server.statefulsetVolumeMounts" . | nindent 12 }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.tableauServer.fluentd.enable }}
        - name: {{ include "tableau-server.fluentdName" . }}
          image: {{ .Values.tableauServer.fluentd.image.repository }}:{{ .Values.tableauServer.fluentd.image.tag }}
          imagePullPolicy: {{ .Values.tableauServer.fluentd.image.pullPolicy }}
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_UUID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TABLEAU_VERSION
            value: {{ .Values.image.tag }}
          - name: ENVIRONMENT
            value: {{ .Values.tableauServer.fluentd.environment }}
          - name: FLUENTD_CONF
            value: "fluentd.conf"
            {{- with .Values.tableauServer.fluentd.envVars }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- with .Values.tableauServer.fluentd.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tableauServer.fluentd.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.tableauServer.fluentd.resources | nindent 12 }}
          volumeMounts:
          - mountPath: {{ .Values.tableauServer.fluentd.logsVolMountPath }}
            name:  data
            readOnly: true
          - mountPath: /var/log
            name: varlog
          - mountPath: /fluentd/etc
            name: fluentd-config
            {{- with .Values.tableauServer.fluentd.volumeMounts }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
        {{- end }}
      volumes:
        {{- include "tableau-server.statefulsetVolumes" . | nindent 8 }}
        {{- if .Values.tableauServer.fluentd.enable }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluentd-config
          configMap:
            name:  {{ include "tableau-server.fluentdName" . }}
        {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      dnsConfig:
        searches:
          - "{{ include "tableau-server.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.dns.clusterDomain }}"
          - "{{ .Release.Namespace }}.svc.{{ .Values.dns.clusterDomain }}"
          - "svc.{{ .Values.dns.clusterDomain }}"
        options:
          - name: ndots
            value: "5"
