#!/bin/bash

# Install MySQL driver
yum install -y /docker/customer-files/drivers/mysql*.rpm
yum -y install mysql-connector-odbc-8.0.32-1.el8
grep -n -F '[MySQL ODBC 8.0 ANSI Driver]' /etc/odbcinst.ini
grep -n -F '[MySQL ODBC 8.0 Unicode Driver]' /etc/odbcinst.ini

# Create JDBC driver directory
mkdir -p /opt/tableau/tableau_driver/jdbc

# Install PostgresSQL driver
cp -rf /docker/customer-files/drivers/jdbc /opt/tableau/tableau_driver

chmod -R 755 /opt/tableau/tableau_driver/jdbc
chown -R tableau /opt/tableau/tableau_driver

# Missing package used by Tableau Server scripts
yum install -y bc

# AWS Cli (used to upload and download backups)
yum install -y less unzip
mkdir -p /tmp/setup
cd /tmp/setup
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install
cd -
rm -rf /tmp/setup
yum remove -y unzip

# Crontab (used to run scripts to maintain a configured tableau server)
yum install -y cronie
