#!/bin/bash

# Install MySQL driver
yum install /docker/customer-files/drivers/mysql*.rpm

# Create JDBC driver directory
mkdir -p /opt/tableau/tableau_driver/jdbc

# Install PostgresSQL driver
cp -rf /docker/customer-files/drivers/jdbc /opt/tableau/tableau_driver

chmod -R 755 /opt/tableau/tableau_driver/jdbc
chown -R tableau /opt/tableau/tableau_driver

# Missing package
yum install -y bc
