#!/bin/bash

# Install MySQL driver
yum install -y /docker/customer-files/drivers/mysql*.rpm
yum -y install mysql-connector-odbc-8.0.32-1.el8
grep -n -F '[MySQL ODBC 8.0 ANSI Driver]' /etc/odbcinst.ini
grep -n -F '[MySQL ODBC 8.0 Unicode Driver]' /etc/odbcinst.ini

# Create JDBC driver directory
mkdir -p /opt/tableau/tableau_driver/jdbc

# Install PostgresSQL driver
cp -rf /docker/customer-files/drivers/jdbc /opt/tableau/tableau_driver

chmod -R 755 /opt/tableau/tableau_driver/jdbc
chown -R tableau /opt/tableau/tableau_driver

# Missing package
yum install -y bc
